CREATE DATABASE `restaurant_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;

CREATE TABLE `restaurant` (
  `RESTAURANT_ID` int(32) NOT NULL AUTO_INCREMENT,
  `RESTAURANT_NAME` varchar(45) NOT NULL,
  `ADDRESS` varchar(45) NOT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `ZIP_CODE` varchar(45) NOT NULL,
  `PRICE_RATING` tinyint(5) NOT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  UNIQUE KEY `RESTAURANT_ID_UNIQUE` (`RESTAURANT_ID`),
  KEY `INDEX` (`RESTAURANT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `category` (
  `RESTAURANT_ID` int(64) NOT NULL,
  `CATEGORY` varchar(45) NOT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  CONSTRAINT `FK_CATEGORY` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `phone` (
  `RESTAURANT_ID` int(64) NOT NULL,
  `PHONE` varchar(45) NOT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  UNIQUE KEY `RESTAURANT_ID_UNIQUE` (`RESTAURANT_ID`),
  CONSTRAINT `FK_PHONE` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `website` (
  `RESTAURANT_ID` int(64) NOT NULL,
  `WEBSITE` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  UNIQUE KEY `RESTAURANT_ID_UNIQUE` (`RESTAURANT_ID`),
  CONSTRAINT `FK_WEBSITE` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `features` (
  `RESTAURANT_ID` int(64) NOT NULL,
  `ORDER_DELIVERY` varchar(1) DEFAULT NULL,
  `ORDER_TAKEOUT` varchar(1) DEFAULT NULL,
  `SERVES_ALCOHOL` varchar(1) DEFAULT NULL,
  `KID_FRIENDLY` varchar(1) DEFAULT NULL,
  `PET_FRIENDLY` varchar(1) DEFAULT NULL,
  `INDOOR` varchar(1) DEFAULT NULL,
  `OUTDOOR` varchar(1) DEFAULT NULL,
  `TAKES_RESERVATIONS` varchar(1) DEFAULT NULL,
  `OFFERS_DEALS` varchar(1) DEFAULT NULL,
  `ACCEPTS_CREDIT_CARDS` varchar(1) DEFAULT NULL,
  `GOOD_FOR_KIDS` varchar(1) DEFAULT NULL,
  `GOOD_FOR_GROUPS` varchar(1) DEFAULT NULL,
  `WAITER_SERVICE` varchar(1) DEFAULT NULL,
  `WHEELCHAIR_ACCESSIBLE` varchar(1) DEFAULT NULL,
  `DOGS_ALLOWED` varchar(1) DEFAULT NULL,
  `OFFERS_MILITARY_DISCOUNT` varchar(1) DEFAULT NULL,
  `FULL_BAR` varchar(1) DEFAULT NULL,
  `HAPPY_HOUR` varchar(1) DEFAULT NULL,
  `SERVES_BREAKFAST` varchar(1) DEFAULT NULL,
  `SERVES_BRUNCH` varchar(1) DEFAULT NULL,
  `SERVES_LUNCH` varchar(1) DEFAULT NULL,
  `SERVES_DINNER` varchar(1) DEFAULT NULL,
  `SERVES_DESSERT` varchar(1) DEFAULT NULL,
  `HAS_LIVE_MUSIC` varchar(1) DEFAULT NULL,
  `STREET_PARKING` varchar(1) DEFAULT NULL,
  `GARAGE_PARKING` varchar(1) DEFAULT NULL,
  `VALET_PARKING` varchar(1) DEFAULT NULL,
  `PRIVATE_LOT` varchar(1) DEFAULT NULL,
  `FREE_WIFI` varchar(1) DEFAULT NULL,
  `ALLOWS_SMOKING` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  KEY `RESTAURANT_ID_INDEX` (`RESTAURANT_ID`) /*!80000 INVISIBLE */,
  CONSTRAINT `FK_FEATURES` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Y = YES\nN = NO';

CREATE TABLE `reviews_directory` (
  `RESTAURANT_ID` int(64) NOT NULL,
  `REVIEW_ID` int(64) NOT NULL,
  PRIMARY KEY (`RESTAURANT_ID`,`REVIEW_ID`),
  UNIQUE KEY `REVIEW_ID_UNIQUE` (`REVIEW_ID`),
  CONSTRAINT `FK_REVIEWS_DIRECTORY` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `menu` (
  `MENU_ID` int(64) NOT NULL AUTO_INCREMENT,
  `RESTAURANT_ID` int(64) NOT NULL,
  PRIMARY KEY (`MENU_ID`,`RESTAURANT_ID`),
  KEY `RESTAURANT_ID_INDEX` (`RESTAURANT_ID`),
  CONSTRAINT `FK_MENU` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `restaurant` (`restaurant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reviews` (
  `REVIEW_ID` int(64) NOT NULL AUTO_INCREMENT,
  `RATING_GIVEN` int(3) DEFAULT NULL,
  `POSTED_REVIEW` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  UNIQUE KEY `review_id_UNIQUE` (`REVIEW_ID`),
  KEY `REVIEW_ID_INDEX` (`REVIEW_ID`) /*!80000 INVISIBLE */,
  CONSTRAINT `FK_REVIEW_ID` FOREIGN KEY (`REVIEW_ID`) REFERENCES `reviews_directory` (`review_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `menu_items` (
  `MENU_ID` int(64) NOT NULL,
  `ITEM_ID` int(64) NOT NULL,
  PRIMARY KEY (`MENU_ID`,`ITEM_ID`),
  KEY `MENU_ID_INDEX` (`MENU_ID`),
  KEY `ITEM_ID_FK_idx` (`ITEM_ID`),
  CONSTRAINT `FK_MENU_ID` FOREIGN KEY (`MENU_ID`) REFERENCES `menu` (`menu_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `item` (
  `ITEM_ID` int(64) NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` varchar(45) NOT NULL,
  `ITEM_PRICE` decimal(6,2) NOT NULL,
  PRIMARY KEY (`ITEM_ID`),
  UNIQUE KEY `ITEM_ID_UNIQUE` (`ITEM_ID`),
  KEY `ITEM_ID_INDEX` (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

