/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

/**
 *
 * @author itsch
 */
public class RestaurantShowFeatures extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantShowFeatures
     */
    public RestaurantShowFeatures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Show Features");

        jLabel2.setText("Restaurant ID:");

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Param[] param = new Param[1];
        param[0] = new Param(idField.getText());
        
        
        RestaurantDisplay RestaurantDisplay = new RestaurantDisplay("SELECT r.RESTAURANT_ID,\n" +
"	     r.RESTAURANT_NAME,\n" +
"         c.CATEGORY,\n" +
"			 f.ORDER_DELIVERY,\n" +
"	   f.ORDER_TAKEOUT,\n" +
"	   f.SERVES_ALCOHOL,\n" +
"	   f.KID_FRIENDLY,\n" +
"	   f.PET_FRIENDLY,\n" +
"	   f.INDOOR,\n" +
"	   f.OUTDOOR,\n" +
"	   f.TAKES_RESERVATIONS,\n" +
"     f.OFFERS_DEALS,\n" +
"		 f.ACCEPTS_CREDIT_CARDS,\n" +
"		 f.GOOD_FOR_KIDS,\n" +
"		 f.GOOD_FOR_GROUPS,\n" +
"		 f.WAITER_SERVICE,\n" +
"		 f.WHEELCHAIR_ACCESSIBLE,\n" +
"		 f.DOGS_ALLOWED,\n" +
"		 f.OFFERS_MILITARY_DISCOUNT,\n" +
"		 f.FULL_BAR,\n" +
"		 f.HAPPY_HOUR,\n" +
"		 f.SERVES_BREAKFAST,\n" +
"		 f.SERVES_BRUNCH,\n" +
"		 f.SERVES_LUNCH,\n" +
"		 f.SERVES_DINNER,\n" +
"		 f.SERVES_DESSERT,\n" +
"		 f.HAS_LIVE_MUSIC,\n" +
"		 f.STREET_PARKING,\n" +
"		 f.GARAGE_PARKING,\n" +
"		 f.VALET_PARKING,\n" +
"		 f.PRIVATE_LOT,\n" +
"		 f.FREE_WIFI,\n" +
"		 f.ALLOWS_SMOKING\n" +
"FROM restaurant AS r\n" +
"INNER JOIN features AS f\n" +
"ON r.RESTAURANT_ID = f.RESTAURANT_ID\n" +
"INNER JOIN category as c\n" +
"ON r.RESTAURANT_ID = c.RESTAURANT_ID "
                + "WHERE r.restaurant_id = ?", param);
        RestaurantDisplay.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantShowFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantShowFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantShowFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantShowFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantShowFeatures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
