/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.util.ArrayList;

/**
 *
 * @author itsch
 */
public class RestaurantSearch extends javax.swing.JFrame {
    private final String TAG = this.getClass().getSimpleName();

    /**
     * Creates new form RestaurantSearch
     */
    public RestaurantSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CityTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CategoryTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Search Restaurants");

        jLabel2.setText("Restaurant Name:");

        jLabel3.setText("City:");

        jLabel4.setText("State:");

        jLabel5.setText("Category:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameTextField)
                            .addComponent(CityTextField)
                            .addComponent(StateTextField)
                            .addComponent(CategoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addComponent(SearchButton))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
        //setting the params to send to RestaurantDisplay
        Param[] params = new Param[4];
        params[0] = new Param(NameTextField.getText());
        params[1] = new Param(CityTextField.getText());
        params[2] = new Param(StateTextField.getText());
        params[3] = new Param(CategoryTextField.getText());
        
        String query = "";
        query += "SELECT r.RESTAURANT_ID,\n"
                + "	     r.RESTAURANT_NAME,\n"
                + "       r.ADDRESS,\n"
                + "       r.CITY,\n"
                + "       r.STATE,\n"
                + "       r.ZIP_CODE,\n"
                + "       p.PHONE,\n"
                + "       w.WEBSITE,\n"
                + "			 c.CATEGORY,\n"
                + "       r.PRICE_RATING\n"
                + "FROM restaurant AS r\n"
                + "LEFT JOIN website AS w\n"
                + "ON r.RESTAURANT_ID = w.RESTAURANT_ID\n"
                + "LEFT JOIN phone AS p\n"
                + "ON w.RESTAURANT_ID = p.RESTAURANT_ID\n"
                + "LEFT JOIN category as c\n"
                + "ON p.RESTAURANT_ID = c.RESTAURANT_ID; ";
                
        
        String query1 = "";
        int valid = 0;
        ArrayList<Param> params1 = new ArrayList<Param>();
        
       
        
        if (!params[0].getString().equals(""))
            {
                valid++;
                query1 += "r.RESTAURANT_NAME = ?";
                params1.add(params[0]);
                
                
            }
        if (!params[1].getString().equals(""))
            {
                if (valid != 0)
                {
                    query1 += " AND ";
                }
                valid++;
                query1 += "r.CITY = ?";
                params1.add(params[1]);
                
            }
        if (!params[2].getString().equals(""))
            {
                if (valid != 0)
                {
                    query1 += " AND ";
                }
                valid++;
                query1 += "r.STATE = ?";
                params1.add(params[2]);
                
            }
        if (!params[3].getString().equals(""))
            {
                if (valid != 0)
                {
                    query1 += " AND ";
                }
                valid++;
                query1 += "r.CATEGORY = ?";
                params1.add(params[3]);
            }
        if (valid != 0)
        {
            query += "WHERE " + query1;
            params = new Param[params1.size()];
            for (int i = 0; i < params.length; ++i)
            {
                params[i] = params1.get(i);
            }
        }
        else
        {
            params = new Param[0];
        }
        query += ";";
        
        
        
        RestaurantDisplay RestaurantDisplay = new RestaurantDisplay(query , params);
        RestaurantDisplay.setVisible(true);
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoryTextField;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField StateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
