/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author itsch
 */
public class RestaurantAddMenu extends javax.swing.JFrame {

    private final String TAG = "RestaurantAddMenu";
    /**
     * Creates new form RestaurantAddMenu
     */
    public RestaurantAddMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ItemIdTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        ShowItemsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Insert Restaurant ID to add to  menu:");

        IdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Item ID:");

        ItemIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIdTextFieldActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ShowItemsButton.setText("Show All Items");
        ShowItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowItemsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Show items on menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ItemIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddButton))
                    .addComponent(ShowItemsButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton))
                .addGap(18, 18, 18)
                .addComponent(ShowItemsButton)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextFieldActionPerformed

    private void ItemIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemIdTextFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(Database.url, Database.user, Database.password);
            Logger.append("Start: " + conn.toString());

            conn.setAutoCommit(false);
            
            PreparedStatement pst = conn.prepareStatement
            ("INSERT INTO menu_items(RESTAURANT_ID, ITEM_ID)\n"
                    + "VALUES(?, ?)");
            
            pst.setInt(1, Integer.valueOf(IdTextField.getText()));
            pst.setInt(2, Integer.valueOf(ItemIdTextField.getText()));
                    
            System.out.println(TAG + ": " + pst);
            Logger.append(pst.toString());


            pst.executeUpdate();
            

            conn.commit();
            Logger.append("End: " + conn.toString());
            conn.close();
            JOptionPane.showMessageDialog(null, "Updated Successfully.");
        }
        catch (SQLException se)
        {
            try{
                if(conn != null)
                    Logger.append("Rollback: " + conn.toString());
                    conn.rollback();
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
            JOptionPane.showMessageDialog(null,TAG + se);
        }
        catch (Exception e)
        {
            Logger.append(e);

            JOptionPane.showMessageDialog(null,TAG + e);
        }
        
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ShowItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowItemsButtonActionPerformed
        // TODO add your handling code here:
        
        RestaurantDisplay RestaurantDisplay = new RestaurantDisplay("SELECT *\n"
                + "FROM item\n"
                , new Param[0]);
        RestaurantDisplay.setVisible(true);
    }//GEN-LAST:event_ShowItemsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Param[] param = new Param[1];
        param[0] = new Param(Integer.valueOf(IdTextField.getText()));

        
        RestaurantDisplay RestaurantDisplay = new RestaurantDisplay("SELECT r.RESTAURANT_ID,\n"
                + "	   r.RESTAURANT_NAME,\n"
                + "       mi.ITEM_ID,\n"
                + "       i.ITEM_NAME,\n"
                + "       i.ITEM_PRICE\n"
                + "FROM restaurant AS r\n"
                + "INNER JOIN menu_items AS mi\n"
                + "ON r.RESTAURANT_ID = mi.RESTAURANT_ID\n"
                + "INNER JOIN item as i\n"
                + "ON mi.ITEM_ID = i.ITEM_ID\n"
                + "WHERE r.RESTAURANT_ID = ?;"
                , param);
        RestaurantDisplay.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantAddMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JTextField ItemIdTextField;
    private javax.swing.JButton ShowItemsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
