/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ericv
 */
public class StartGUI extends javax.swing.JFrame {
    private final String TAG = this.getClass().getSimpleName();


    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        DisplayRecordsButton = new javax.swing.JButton();
        UpdateRestaurantButton = new javax.swing.JButton();
        AddRestaurantButton = new javax.swing.JButton();
        SearchRestaurantButton = new javax.swing.JButton();
        UpdateFeaturesButton = new javax.swing.JButton();
        ShowFeaturesButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();
        InserReviewButton = new javax.swing.JButton();
        DeleteRestaurantButton = new javax.swing.JButton();
        ShowReviewsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Restaurant Database");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        DisplayRecordsButton.setText("Display Restaurants");
        DisplayRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 180, 50));

        UpdateRestaurantButton.setText("Update Restaurant Entry");
        UpdateRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRestaurantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 50));

        AddRestaurantButton.setText("Add Restaurant");
        AddRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRestaurantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 50));

        SearchRestaurantButton.setText("Search Restaurants");
        SearchRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRestaurantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 180, 50));

        UpdateFeaturesButton.setText("Update Features");
        UpdateFeaturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateFeaturesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateFeaturesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 180, 50));

        ShowFeaturesButton.setText("Show Features");
        ShowFeaturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFeaturesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowFeaturesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 180, 50));

        ExportButton.setText("Export to CSV");
        ExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        InserReviewButton.setText("Insert Review");
        InserReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserReviewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InserReviewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 180, 50));

        DeleteRestaurantButton.setText("Delete Restaurant");
        DeleteRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRestaurantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteRestaurantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 180, 50));

        ShowReviewsButton.setText("Show Reviews");
        ShowReviewsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReviewsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowReviewsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 830, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRecordsButtonActionPerformed
//Link to new Jframe
        RestaurantDisplay RestaurantDisplay = new RestaurantDisplay("SELECT r.RESTAURANT_ID,\n"
                + "	     r.RESTAURANT_NAME,\n"
                + "       r.ADDRESS,\n"
                + "       r.CITY,\n"
                + "       r.STATE,\n"
                + "       r.ZIP_CODE,\n"
                + "       p.PHONE,\n"
                + "       w.WEBSITE,\n"
                + "       r.PRICE_RATING\n"
                + "FROM restaurant AS r\n"
                + "INNER JOIN website AS w\n"
                + "ON r.RESTAURANT_ID = w.RESTAURANT_ID\n"
                + "INNER JOIN phone AS p\n"
                + "ON w.RESTAURANT_ID = p.RESTAURANT_ID;", new Param[0]);
        RestaurantDisplay.setVisible(true);
    }//GEN-LAST:event_DisplayRecordsButtonActionPerformed

    private void UpdateRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRestaurantButtonActionPerformed
        // TODO add your handling code here:
        RestaurantUpdate restaurantUpdate = new RestaurantUpdate();
        restaurantUpdate.setVisible(true);
    }//GEN-LAST:event_UpdateRestaurantButtonActionPerformed

    private void AddRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRestaurantButtonActionPerformed
        // TODO add your handling code here:
        RestaurantAdd restaurantAdd = new RestaurantAdd();
        restaurantAdd.setVisible(true);
    }//GEN-LAST:event_AddRestaurantButtonActionPerformed

    private void SearchRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRestaurantButtonActionPerformed
        // TODO add your handling code here:
        RestaurantSearch restaurantSearch = new RestaurantSearch();
        restaurantSearch.setVisible(true);
    }//GEN-LAST:event_SearchRestaurantButtonActionPerformed

    private void UpdateFeaturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateFeaturesButtonActionPerformed
        // TODO add your handling code here:
        RestaurantAddFeatures temp = new RestaurantAddFeatures();
        temp.setVisible(true);
    }//GEN-LAST:event_UpdateFeaturesButtonActionPerformed

    private void ShowFeaturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFeaturesButtonActionPerformed
        // TODO add your handling code here:
        RestaurantShowFeatures temp = new RestaurantShowFeatures();
        temp.setVisible(true);
    }//GEN-LAST:event_ShowFeaturesButtonActionPerformed

    private void ExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportButtonActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://DESKTOP-Q1NBULV:3306/restaurant_db?zeroDateTimeBehavior=convertToNull";
        String user = "charlie";
        String password = "myPassword";
        
        Connection conn = null;
        
        String Query = "SELECT * FROM restaurant;";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, password);
            
            Export.printToCsv(Export.fetchDataFromDatabase(Query, conn), "Export.csv");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,TAG + e);
        }
    }//GEN-LAST:event_ExportButtonActionPerformed

    private void InserReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserReviewButtonActionPerformed
        // TODO add your handling code here:
        RestaurantInsertReview temp = new RestaurantInsertReview();
        temp.setVisible(true);
    }//GEN-LAST:event_InserReviewButtonActionPerformed

    private void DeleteRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRestaurantButtonActionPerformed
        // TODO add your handling code here:
        RestaurantDelete temp = new RestaurantDelete();
        temp.setVisible(true);
    }//GEN-LAST:event_DeleteRestaurantButtonActionPerformed

    private void ShowReviewsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReviewsButtonActionPerformed
        // TODO add your handling code here:
        RestaurantShowReviews temp = new RestaurantShowReviews();
        temp.setVisible(true);
    }//GEN-LAST:event_ShowReviewsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRestaurantButton;
    private javax.swing.JButton DeleteRestaurantButton;
    private javax.swing.JButton DisplayRecordsButton;
    private javax.swing.JButton ExportButton;
    private javax.swing.JButton InserReviewButton;
    private javax.swing.JButton SearchRestaurantButton;
    private javax.swing.JButton ShowFeaturesButton;
    private javax.swing.JButton ShowReviewsButton;
    private javax.swing.JButton UpdateFeaturesButton;
    private javax.swing.JButton UpdateRestaurantButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setVisisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
